### ISSUE TITLE
Home page loading performance

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#1]
Our homepage performs poorly with chrome performance audit (inspect -> audit -> performance). I tried to improve it but did not know exactly how to do it. I however noticed that [all four tabs are loaded when the page is ready ](https://github.com/vatlab/sos-docs/blob/master/js/sos_script.js#L2), so I am wondering if it can be changed to load on demand (e.g. load only the first page, and the rest when the tab is pressed), as discussed [here](https://stackoverflow.com/questions/8456974/how-to-use-ajax-loading-with-bootstrap-tabs).

![image](https://user-images.githubusercontent.com/9889312/31258922-69632c34-aa08-11e7-90e2-d5c2cba8f267.png)

**Comment by jma7** [comment]
I got 61 Performance when I run at home, I will take a look anyway. The links in the index column in documentation pages are not working though.

**Comment by BoPeng** [comment]
We have separated the sos repo into 10+ repos and moved the docs to `sos-docs`. The docs should work now though.

**Comment by BoPeng** [comment]
61 is not that high, right? :-)

The progressive web app asks us to provide a snapshot page to be viewed on cell phone, which is an interesting idea but not sure if it is easy to add (sounds like a manifest file is enough).

**Comment by BoPeng** [comment]
The funny/scary thing I heard is that google will actually give you lower ranking score if your website does not score well on those tests.
