### ISSUE TITLE
Documentation Typo: Uisng the markdown kernel

### ISSUE THREAD

**Issue by GadgetSteve** [vatlab/sos-docs#104]
Reasonably sure that this should read:
Using the markdown kernel

**Comment by GadgetSteve** [comment]
The following patch should resolve (possibly overkill).
[patch#104.patch](https://github.com/user-attachments/files/16541315/patch.104.patch)

**Comment by BoPeng** [comment]
Thanks. Applied. https://github.com/vatlab/sos-docs/commit/80a961425d9f5673b67a59b67bbb734b6217c6d1
