### ISSUE TITLE
Social icons keep color after clicking.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#18]
Right now if we click an icon and goes to another page, the icon keeps its color even after we return to the page. It is better to change color back to white as soon as the icon loses focus.

**Comment by kqwang123** [comment]
Where is the code?

**Comment by BoPeng** [comment]
[html](https://github.com/vatlab/sos-docs/blob/master/index.html#L62) and [css](https://github.com/vatlab/sos-docs/blob/master/css/testtab.css) (might be in another file). Use chrome and inspect element to find out where the css is.

**Comment by Fruitmc273** [comment]
what is this

**Comment by kqwang123** [comment]
ok

**Comment by BoPeng** [comment]
Try to figure out by yourself. Basically, you will need to

1. check out the repo
2. use chrome to open local index.html
3. use chrome to find relevant css code and
4. make changes to css file
5. If everything works, push the changes to the repo
