### ISSUE TITLE
Changing website title 

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#19]
Not sure where but I can recall a website with a main title and several alternating texts, something like

```
Learn R
Learn Python
Learn C#
```

with `R`, `Python`, `C#` appear in turn in a type-out fashion. I suppose we can use a similar technic to add `Workflow Engine` and `Notebook` to the title:

```
SoS Workflow Engine
SoS Notebook
```

**Comment by BoPeng** [comment]
JS example is available [here](http://jsfiddle.net/Dogbert/vF4rj/3/)

**Comment by Qwertyuiop21672** [comment]
Interesting
This may take me a few minutes :P

**Comment by BoPeng** [comment]
We can alternate between

```
SoS Workflow Engine
```
and
```
SoS Multilingual Notebook
```
or
```
SoS Polyglot Notebook
```

Polyglot is shorter but less popular than multilingual.

**Comment by BoPeng** [comment]
```
SoS
```
and
```
Polyglot Notebook
```
need to be bottom-aligned.
