### ISSUE TITLE
Add shade around images on homepage

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#20]
The images on the [SoS Homepage](https://vatlab.github.io/sos-docs/) does not have shade. It would be good to add shade as follows:

![image](https://user-images.githubusercontent.com/9889312/34755774-f4441254-f58b-11e7-8477-053245e9a6a2.png)

Hint: Use css. There is no need to change image themselves.

**Comment by BoPeng** [comment]
he shadow is too dark, and I like shadow in all four edges (see picture above)...

Also, please cite the ticket number in the commit message so that the commit can be shown in the issue.

**Comment by Qwertyuiop21672** [comment]
i changed it

**Comment by BoPeng** [comment]
but you did not push it. Also, please add "#20" to the end of commit message so that your commit can be linked to this ticket.
