### ISSUE TITLE
Remote tasks option `name` and / or `tags`?

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#22]
[This page](https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html) mentions both options `tags` and `name`. Option `tags` was documented as a separate section; `name` was not documented as such but was referred to, and one can infer its usage. I think I can tell their difference, but I'm not sure about it 100%. Shouldn't `name` also be documented?

**Comment by BoPeng** [comment]
Name is deprecated as its function overlaps with tags.

**Comment by BoPeng** [comment]
I will need to fix the doc.

**Comment by gaow** [comment]
Oh Ok but currently:

> job_name: Interpolated value of runtime option name

What happens when `name` is removed? `job_name` will become `task_id.{'.'.join(tags)}`

**Comment by BoPeng** [comment]
Job name will be task name and users are encouraged to use `sos status` to track tasks since its output contains workflow ID, step ID, sample ID (if using tags) etc.

**Comment by BoPeng** [comment]
Fixed.

Note that option `tags` is not passed as template variables so it cannot be used to construct job name. This is by design because `tags` are optional so it would be difficult to use them in job template.
