### ISSUE TITLE
Update GIF files under homepage to use our new logo.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#24]
The gif files from our homepage are outdated because the introduction of new logo (vatlab/sos-notebook#50).

1. Find the source code of the GIF files under [examples](https://github.com/vatlab/SoS/tree/master/development/docker-notebook/examples)
2. Create notebooks, enter the cells one by one and take screenshots. The screenshot should be taken without shadow because the homapge uses css to add shadows
3. Replace existing screenshots under [src/media](https://github.com/vatlab/sos-docs/tree/master/src/media) （e.g.  under directory sos_syntax ) and commit.
4, Add annotations (call out bubbles) to screenshots Iperhaps use better font/style). I used preview but there are other and perhaps better tools. Commit again.
5. Convert the PNG files to gif. Using ImageMagick convert command, with command 
```
convert -delay 300 -loop 0 *.png animation.gif
```
5. Replace corresponding files under [doc/media](https://github.com/vatlab/sos-docs/tree/master/doc/media) with the new gif files. These are files used by the homepage (and our blog).

**Comment by BoPeng** [comment]
We could also edit existing PNG files and cover the old logo with the [new one](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/logo-64x64.png). If we still have all the source png files available.

**Comment by BoPeng** [comment]
@tutudong We are working on better cell-level language-specific syntax highlighting (vatlab/sos-notebook#52), Please wait until vatlab/sos-notebook#55 is resolved before you proceed.

**Comment by BoPeng** [comment]
vatlab/sos-notebook#55 is resolved. You can update and try again. Let me know if syntax highlighting does not work as expected.

**Comment by BoPeng** [comment]
You will need to `git update` the latest `sos-notebook` repository, run `python setup.py install`, and then `python sos_notebook.install`.

**Comment by tutudong** [comment]
I have some problems on the SoS workflow.
<img width="1280" alt="problem" src="https://user-images.githubusercontent.com/36909003/39154556-337e0194-4714-11e8-81d6-025ff17c64ea.png">
`%sosrun analysis `
can not execute the workflow analysis and 
`%preview --workflow`
does not show any content.

**Comment by BoPeng** [comment]
Confirmed. There has been some big changes recently to accommodate JupyterLab extension. I will fix it soon.

**Comment by BoPeng** [comment]
You might have to remove all previous versions of sos-notebook under python site-packages and re-install.

**Comment by gaow** [comment]
This may achieve the same: run `pip uninstall sos-notebook` until there is nothing left.

**Comment by tutudong** [comment]
I removed all previous versions and installed again, but still `%sosrun` is not working as previously.
<img width="1280" alt="screen shot 2018-04-24 at 10 03 17 am" src="https://user-images.githubusercontent.com/36909003/39196031-c40e8e80-47a6-11e8-9f5c-d521433ff1ff.png">
`%sosrun` can not execute the above cell.

**Comment by BoPeng** [comment]
Can you drop by my office with your laptop?

**Comment by tutudong** [comment]
On my way.

**Comment by BoPeng** [comment]
@tutudong The font in your image is much smaller than the original ones which makes them less visible, especially on cellphone. Could you adjust them?

![image](https://user-images.githubusercontent.com/9889312/39412260-512eb5ba-4bdf-11e8-8612-c6553721e125.png)

![image](https://user-images.githubusercontent.com/9889312/39412246-21917f18-4bdf-11e8-9755-732b208f79ab.png)

**Comment by tutudong** [comment]
OK. Will do it.

**Comment by BoPeng** [comment]
You might have noticed that the left panel of your gifs has a big gap at the top, which is likely caused by the increase of font and shrink of window. The method I used to prevent this was to use a decent sized window and larger font, which not only fixes the gap, but also reduces the relative size of the tile bar and menu bar (i.e. non-informative repetitive areas) thus increases the areas of interest...
