### ISSUE TITLE
Sticky header cover tab content

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#33]
With the current css/js set up, we have

```
header
nagivation - sticky at top 
tab-content
```
The tab-content would go under header while scrolling. This is usually not a problem but when we jump to a section (e.g. using the dropdown menu), the anchor point (header) would be under the header.

This is basically the problem described in https://stackoverflow.com/questions/9677894/header-div-stays-at-top-vertical-scrolling-div-below-with-scrollbar-only-attach but I failed to adapt the solutions to our website with the header and sticky navigation bar.

**Comment by jma7** [comment]
Fixed based on this link.
https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

**Comment by BoPeng** [comment]
Great. Thanks. I guess I did not google long enough. :smile:

**Comment by BoPeng** [comment]
The patch was overwritten because you updated HTML files, not ipynb files. Let me see if I can add the changes to ipynb or the templates.

**Comment by BoPeng** [comment]
The css trick introduced [here](https://css-tricks.com/hash-tag-links-padding/) could be used. There is link that does not well, perhaps because of collision between `#Documentation` on two tabs. This does not really matter though.
