### ISSUE TITLE
Re-factor notebook and workflow documentation page

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#48]
With the User Guide in place I wonder what will be the scope of notebook and workflow documentation pages. Other than vidoes and examples, should we remove the `techinical details` part from User Guide and put them under these parts? Also how about links to SoS related slides?

**Comment by BoPeng** [comment]
I think the current "documentation" is more or less "reference manual" with examples, and is very similar to the current "tutorials". There will be

1. Users guide, which will be tutorials with examples, organized by topics, with cross-references.
2. Reference manual, which will be output of `help(func)` and `sos run -h` etc, will be very dry but presented for clarity and completeness. They should generally be machine - generated in the sense that they should more or less be generated by commands and `pydoc` etc.

It does not really matter if the reference manual should be separated or in the details section of the user's guide. My concern is more on what to do with the `workflow` and `notebook pages once the documentations and tutorials are removed. Perhaps we should move some blog content there... 

But all these will take pretty long time to do so we do not have to decide on the organization now.

**Comment by BoPeng** [comment]
Original documentation and tutorials are removed.
