### ISSUE TITLE
Making it easier for users to update our documentation.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#49]
Right now updates to our documentation has to be done with

1. install sos and sos notebook locally.
2. check out the `sos-docs` repository locally
2. edit the documents in Jupyter Notebook or JupyterLab
3. commit only the changes or after running `development/update_website.

I wonder if we can

1. Add a edit button to our tutorial pages
2. the button will lead to our live server on which there is a fresh copy of `sos-docs`
3. users can edit the document online
4. using a magic or something magical, create a push request to sos-docs
5. we accept the push request, which would trigger `update-website` and also update the HTML version

**Comment by BoPeng** [comment]
Related projects could include [colaborary](https://colab.research.google.com/notebooks/welcome.ipynb#recent=true) and [binder](https://github.com/binder-examples/jupyter-sos) but none of them seems to allow easy creation of PRs.

Perhaps the following can work:

1. We create a separate github account.
2. Clone sos-docs to our live server with that account, and save credential 
3. Mount `sos-docs` to docker image
4. Create a short cut to a script that creates a PR using github command line tool.

So in this way if we somehow point user to a specifc page in the docker image, we can instruct users to run a command to the left panel (or create a dedicated button) to create a PR.

**Comment by gaow** [comment]
Yes I think it should work. But we should also make sure the live server document is always up to date; that is, automatic `git pull` before editing. I'm not sure how that can be done easily?

**Comment by BoPeng** [comment]
Problems:

1. [tmpnb](https://github.com/jupyter/tmpnb) is no longer maintained, but I do not know how much work it would be to switch to binderhub.
2. There is no easy way to point to a specific file so users would have to find specific file.
3. Some cron job is needed to make sure the forked doc is in sync with the upstream, but not when the doc is being edited.
4. Need to install [HUB](https://hub.github.com/) to make create PR from command line.

**Comment by BoPeng** [comment]
It someone has time, I think [JupyterHub](https://github.com/jupyterhub/jupyterhub) + [tmpauthenticator](https://github.com/jupyterhub/tmpauthenticator) is the way to go.

**Comment by sosdocs** [comment]
A separate github account `sosdocs` is created. After saving credentials, run

```
git remote add upstream https://github.com/vatlab/sos-docs
hub pull-request -m ''some message"
```
would create the pull request (#50).

**Comment by BoPeng** [comment]
https://github.com/vatlab/sos-docs/tree/master/development/docker

1. A docker image is added to have github cli included.
2. A `create-branch` and a `create-pr` scripts are added to the docker.

Basically,

1. When a docker instance is created, it will create a new random branch, fetch and merge `sos-docs/master`
2. After the user modifies the file, s/he can run command `create-pr` to run `update-website` to update scripts for the branch, then create a pr from the branch to `sos-docs/master`. 

Remaining technical issue:
1. Figure out how to open a jupyter instance and open a file directly.

After that,
1. set up a jupyter hub server
2. make sure the create-pr workflow works
3. Add an `edit` button to the top right of each tutorial

**Comment by BoPeng** [comment]
The last missing piece has been found, thanks to the JupyterHub team,

> There's a URL `https://hub-host/hub/user-redirect/...` that redirects users to their own server, which allows you to share a single link that any user can open that file in their own server. e.g.

```
https://myjupyterhub.biz/hub/user-redirect/notebooks/filename.ipynb
```

**Comment by BoPeng** [comment]
Almost there, but not quite.

See https://github.com/vatlab/sos-docs/tree/master/development/jupyterhub for ideas.

What has been done, 
1. Installed a jupyterhub server to replace the old `tmpnb` installation.
2. Added a button to the top right corner of tutorials (e.g. [sos-in-notebook.html](https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook.html).
3. Clicking on the button opens the correct file on the live server.

Remaining problems:
1. The mounted image is readonly. Not sure how to resolve this. We could try to manually mount the directory and see how to fix it

```
docker run --rm -it -v /home/sos/sos-docs:/home/jovyan/sos-docs -p 8000:8000 mdabioinfo/sos-docs
``` 
The [dockerspawner source code](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L307) said something like permission but not sure how to use it. 

The code to mount the directory is [here](https://github.com/vatlab/sos-docs/blob/master/development/jupyterhub/docker-jupyterhub/jupyterhub_config.py#L29)

2. There can be some `kernel error`, possibly when there are more than one instance of `mdabioinfo:sos-docs` image are running. Should fix this after 1.

**Comment by gaow** [comment]
Looks nice. But another issue I noticed is that I tested it last night running some workflow under the `examples` folder. The output are not deleted after I quit and reopen the server. It is still there now. This can be problematic -- is there a mechanism to clean up specific folders? Or, to put everything in GIT and run `git clean -df` automatically before each session starts?

**Comment by BoPeng** [comment]
Yes, `git clean -df` should be applicable in this case but sharing the `sos-docs` folder is problematic in general. I mean, imagine the rare case that two users edits the doc at the same time...

So the only safe way is to get a refresh `sos-docs` repo inside docker so that everyone has their his own copy, and everything will be destroyed when the docker instance is released. It can be reasonably fast if we have a recent enough copy in docker and opening the instance will only trigger a fetch to catch up the latest.

**Comment by gaow** [comment]
>  if we have a recent enough copy in docker and opening the instance will only trigger a fetch to catch up the latest.

I suppose we can use a cron job for it? The cron job should first check if there are active connections to the live server, and update the docker image if there is no active connections? eg

```
while True
 if no_active_connection():
   update_docker()
    break
 sleep(600)
``` 

and we set it to run daily?

**Comment by BoPeng** [comment]
We may not even have to worry about active instances because we are updating the `sos-docs` image so that it can be used the next time when it is spawned by jupyterhub. But I do not really know if it is ok to update an image while it is being used. Some google work is needed.

**Comment by BoPeng** [comment]
@gaow @jma7 @HenryLeongStat @ChrisWakefield

I have completed this online-editing feature for sos-docs. Basically, when you visit any of the sos docs documentation, there will be an edit button to the top right corner of the page. If you spot anything wrong of the page, please click the edit button, modify it, and type

```
!create-pr <Shift-Enter>
```
in the console panel to submit a PR.

**Comment by gaow** [comment]
This is very nice! It would be a nice software by itself if the set-up is streamlined to include converting random jupyter notebooks to a website.

**Comment by BoPeng** [comment]
Yes, this can be a feature of the project you have in mind, but for later. Right now, I think we need to

1. Use it for a while to see how reliable this process is
2. Set up a cron job to update docker image
3. Check resource usage and improve the jupyterhub server. For example, there is currently no limit on the number of notebook servers.

**Comment by gaow** [comment]
> Check resource usage and improve the jupyterhub server.

If we can keep the resource usage under control then all tutorials are also live examples, if we want to advertise it and let users interact with those chunks of workflows directly. My point is that this is potentially more than an edit feature.

**Comment by BoPeng** [comment]
Yes, I did not apply the template to our examples but in theory we can do that so all our examples could be run on the live server. The problem is that we have a single template for all features (navigation button etc) but the examples only need one and perhaps with a different style.

**Comment by jma7** [comment]
```
Syncing with upstream master
Creating a new branch FNZ1G7
Committing changes
Pushing to branch FNZ1G7
Creating pull request

Error creating pull request: Unprocessable Entity (HTTP 422)
No commits between vatlab:master and sosdocs:FNZ1G7
```
Got this message when I tried to fix a typo.

**Comment by BoPeng** [comment]
@gaow Could you try the `create-pr` command and see if it works for you? @jma7 was having trouble.

**Comment by gaow** [comment]
Loos like it does? https://github.com/vatlab/sos-docs/pull/65

**Comment by BoPeng** [comment]
I got the PR and merged it. So the problem might related to repository not in sync with the master? I have asked @jma7 to use option `-v` to show output of command next time when things go wrong.
