### ISSUE TITLE
Upload manuscript examples to sos notebook server?

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#5]
I think this would be idea, but then we'lll have to install all required files / tools to our docker image. What's the best way to do it?

**Comment by BoPeng** [comment]
The server now has all the kernels set up, but not necessarily the tools (e.g. R library). It is already very big so I  have just [added a bioconductor package](https://github.com/vatlab/SoS/blob/master/development/docker-notebook/Dockerfile#L88) to it for the video I will be recording and you can add the package you will need in a similar fashion.

**Comment by BoPeng** [comment]
You can also copy the examples to the docker image using the [COPY command](https://github.com/vatlab/SoS/blob/master/development/docker-notebook/Dockerfile#L90), or you can run a `git checkout` command in Dockerfile because the examples are now in another repository.

**Comment by gaow** [comment]
Good to know! I may do it after next week as I'm cramming for multiple things then will leave for 2 meetings (one is ASHG!) next week.

**Comment by Qwertyuiop21672** [comment]
is this for me?

**Comment by BoPeng** [comment]
No. Another one. You could remove prompt etc when screen is small.

**Comment by Qwertyuiop21672** [comment]
ok
