### ISSUE TITLE
Live edit does not work after moving live server to sosworkflows.com

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-docs#92]
Need to update the template,

**Comment by BoPeng** [comment]
@joannfeng The sos documentation https://vatlab.github.io/sos-docs/ was written in Jupyter and converted to HTML using customized templates.

We have recently moved our live server (see https://vatlab.github.io/sos-docs/running.html#Live-SoS-server) from a machine in MD Anderson to a dedicated machine sosworkflows.com. The server has been coded in documentations such as https://vatlab.github.io/sos-docs/doc/user_guide/sos_python.html for people to suggest updates to the documentation (top right corner) and it does not work now.

You will need to 
1. create a conda env for sos ,and install sos, sos notebook etc. Read the documentation for some basics about the tools.
2. check out this repo.
3. edit https://github.com/vatlab/sos-docs/blob/master/src/templates/parts/edit_button.tpl and replace the original IP-based URL to sosworkflows.com.
4. Run https://github.com/vatlab/sos-docs/blob/master/development/update-website to update the HTML files
5. create a PR.

**Comment by BoPeng** [comment]
@joannfeng It appears that the :8000 still in the HTML files... Please use `update_website -s force` to force regenerate the HTML files.

The problem is that the script tracks dependencies but does not consider this particular `tpl` file as dependency, so it ignores the HTML file when this template file is changed.

**Comment by joannfeng** [comment]
I see. I was wondering why so many steps were skipped the second time. I
created a new PR - could you please check to see if it worked?

**Comment by BoPeng** [comment]
Should work now.
